version: '3.8'
services:
  therap1:
    image: cuongld2/nextjs-therap-1
    ports:
      - "3000:3000"
  
  # therap2:
  #   image: cuongld2/nextjs-therap-2
  #   ports:
  #     - "3001:3001"

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
      # - 8001:8001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf