version: '3.8'
services:
  therap1:
    image: cuongld2/nextjs-therap-1
  
  therap2:
    image: cuongld2/nextjs-therap-2

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf